# Generated by Django 2.0.5 on 2018-05-29 08:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_from', models.CharField(max_length=30)),
                ('trip_to', models.CharField(max_length=30)),
                ('datetime', models.DateTimeField()),
                ('free_seats', models.IntegerField()),
                ('car', models.CharField(max_length=30)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
