# Generated by Django 2.0.5 on 2018-05-30 10:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blabla', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='car',
            field=models.CharField(max_length=30, verbose_name='Машина:'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='datetime',
            field=models.DateTimeField(verbose_name='Время отбытия'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='free_seats',
            field=models.IntegerField(verbose_name='Свободные места:'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_from',
            field=models.CharField(max_length=30, verbose_name='Место отправления:'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_to',
            field=models.CharField(max_length=30, verbose_name='Место прибытия:'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
