# Generated by Django 2.0.5 on 2018-05-30 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blabla', '0002_auto_20180530_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='creator',
            field=models.IntegerField(default=0, verbose_name='Заявитель'),
        ),
    ]
