# Generated by Django 2.0.6 on 2018-06-03 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blabla', '0003_trip_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='free_seats',
            field=models.PositiveIntegerField(verbose_name='Свободные места:'),
        ),
    ]
