# Generated by Django 2.0.5 on 2018-06-08 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blabla', '0004_auto_20180603_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='phone',
            field=models.CharField(blank=True, default='+7(978)', max_length=15, verbose_name='Номер телефона'),
        ),
    ]
