# Generated by Django 2.0.5 on 2018-06-08 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blabla', '0005_trip_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='phone',
            field=models.CharField(blank=True, default='+7', max_length=15, verbose_name='Номер телефона'),
        ),
    ]
