# Generated by Django 2.0.6 on 2018-06-12 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blabla', '0006_auto_20180608_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='phone',
            field=models.CharField(blank=True, default='+7', max_length=16, verbose_name='Номер телефона'),
        ),
    ]
